#!/bin/sh
# postinst script for smsc-test-server
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

#DEBHELPER#

case "$1" in
    configure)

        # Create user if it doesn't exist.
        if ! id smsc-test-server > /dev/null 2>&1 ; then
            adduser --system --no-create-home --disabled-password --disabled-login --group --home /var/run/smsc-test-server smsc-test-server
        fi

        chown -R smsc-test-server:smsc-test-server /usr/share/ostdlabs/smsc-test-server

        ENV_TYPE="testing"
        if [ -r /usr/share/ostdlabs/smsc-test-server/environment ] ; then
            ENV_TYPE=$(cat /usr/share/ostdlabs/smsc-test-server/environment)
        fi

        if [ -r /usr/share/ostdlabs/smsc-test-server/nginx/smsc-test-server.${ENV_TYPE} ]; then
            ln -sf /usr/share/ostdlabs/smsc-test-server/nginx/smsc-test-server.${ENV_TYPE} /etc/nginx/sites-available/smsc-test-server
            ln -sf /etc/nginx/sites-available/smsc-test-server /etc/nginx/sites-enabled/smsc-test-server
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0